#
#--------------------------------------------------------------------------
#Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
#Safe Autonomy Dynamics.
#
#This is a US Government Work not subject to copyright protection in the US.
#
#The use, dissemination or disclosure of data in this file is subject to
#limitation or restriction. See accompanying README and LICENSE for details.
#---------------------------------------------------------------------------
#
site_name: Safe Autonomy Dynamics
site_author: Safe Autonomy Team
repo_url: https://github.com/act3-ace/rta/safe-autonomy-dynamics
docs_dir: "docs"
site_url: https://github.com/act3-ace/
edit_uri: blob/main/docs/
site_dir: site
site_description: "The following python project provides various dynamics models in the air and space domain."

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
  - autorefs
  - gen-files:
      scripts:
        - docs/gen_ref_nav.py  # or any other name or path
  - section-index
  - pdf-export:
      verbose: false
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
      combined: true


theme:
  name: material
  icon:
    logo: material/currency-sign
  features:
  - navigation.tabs
  - navigation.top
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode


extra_css:
  - css/style.css
  - css/material.css
  - css/mkdocstrings.css


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.arithmatex:  # MathJax (latex)
      generic: true

extra_javascript:
  # Mermaid
  - https://unpkg.com/mermaid@8.4.2/dist/mermaid.min.js
  # MathJax (latex)
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

handlers:
  python:
    setup_commands:
    - import sys
    - sys.path.append("docs")
    selection:
      new_path_syntax: yes
    import:  # demonstration purpose in the docs
      - https://docs.python-requests.org/en/master/objects.inv

nav:
  - "Introduction": index.md
  - "Install": install.md
##  - "Changelog": change_log.md
##  - "License": license.md
  - "API":
      - api/index.md
      - "external":
          - api/external/index.md
          - "aerobench":
              - api/external/aerobench/index.md
              - "controlled_f16": reference/external/aerobench/controlled_f16.md
              - "util": reference/external/aerobench/util.md
              - "lowlevel":
                  - api/external/aerobench/lowlevel/index.md
                  - "adc": reference/external/aerobench/lowlevel/adc.md
                  - "cl": reference/external/aerobench/lowlevel/cl.md
                  - "clf16": reference/external/aerobench/lowlevel/clf16.md
                  - "cm": reference/external/aerobench/lowlevel/cm.md
                  - "cn": reference/external/aerobench/lowlevel/cn.md
                  - "conf16": reference/external/aerobench/lowlevel/conf16.md
                  - "cx": reference/external/aerobench/lowlevel/cx.md
                  - "cy": reference/external/aerobench/lowlevel/cy.md
                  - "cz": reference/external/aerobench/lowlevel/cz.md
                  - "dampp": reference/external/aerobench/lowlevel/dampp.md
                  - "dlda": reference/external/aerobench/lowlevel/dlda.md
                  - "dldr": reference/external/aerobench/lowlevel/dldr.md
                  - "dnda": reference/external/aerobench/lowlevel/dnda.md
                  - "dndr": reference/external/aerobench/lowlevel/dndr.md
                  - "low_level_controller": reference/external/aerobench/lowlevel/low_level_controller.md
                  - "morellif16": reference/external/aerobench/lowlevel/morellif16.md
                  - "pdot": reference/external/aerobench/lowlevel/pdot.md
                  - "rtau": reference/external/aerobench/lowlevel/rtau.md
                  - "subf16_model": reference/external/aerobench/lowlevel/subf16_model.md
                  - "tgear": reference/external/aerobench/lowlevel/tgear.md
                  - "thrust": reference/external/aerobench/lowlevel/thrust.md
      - "base models": reference/base_models.md
      - "cwh":
          - api/cwh/index.md
          - "point_model": reference/cwh/point_model.md
          - "rotational_model": reference/cwh/rotational_model.md
          - "sixdof_model": reference/cwh/sixdof_model.md
      - "dubins": reference/dubins.md
#      - reference/SUMMARY.md  # API "Table of Contents"

