#--------------------------------------------------------------------------
#Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
#Reinforcement Learning (RL) Core AFSIM Extension.
#
#This is a US Government Work not subject to copyright protection in the US.
#
#The use, dissemination or disclosure of data in this file is subject to
#limitation or restriction. See accompanying README and LICENSE for details.
#---------------------------------------------------------------------------
site_name: Safe Autonomy Dynamics
site_author: Safe Autonomy Team
repo_url: https://git.act3-ace.com/rta/safe-autonomy-dynamics
docs_dir: "docs"
site_url: https://git.act3-ace.com/
edit_uri: blob/main/docs/
site_dir: site
site_description: "The following python project provides various dynamics models in the air and space domain."

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
  - autorefs
  - gen-files:
      scripts:
        - docs/gen_ref_nav.py  # or any other name or path
  - section-index
  - pdf-export:
      verbose: false
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
      combined: true


theme:
  name: material
  icon:
    logo: material/currency-sign
  features:
  - navigation.tabs
  - navigation.top
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode


extra_css:
  - css/style.css
  - css/material.css
  - css/mkdocstrings.css


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.arithmatex:  # MathJax (latex)
      generic: true

extra_javascript:
  # Mermaid
  - https://unpkg.com/mermaid@8.4.2/dist/mermaid.min.js
  # MathJax (latex)
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

handlers:
  python:
    setup_commands:
    - import sys
    - sys.path.append("docs")
    selection:
      new_path_syntax: yes
    import:  # demonstration purpose in the docs
      - https://docs.python-requests.org/en/master/objects.inv

nav:
  - "Introduction": index.md
  - "Install": install.md
##  - "Changelog": change_log.md
##  - "License": license.md
  - "API":
      - api/index.md
      - "base models": reference/base_models.md
      - "cwh": reference/cwh.md
      - "dubins": reference/dubins.md
#      - reference/SUMMARY.md  # API "Table of Contents"

